### ISSUE TITLE
Compile fails with Scala 2.10

### ISSUE THREAD

**Issue by sutram** [julianpeeters/avro-scala-macro-annotations#13]
My code compiles fine with Scala 2.11.6 but fails with Scala 2.10

Given the following code:

```scala
package com.twc.needle.domain

import com.julianpeeters.avro.annotations._

import org.apache.avro.specific.SpecificDatumWriter
import org.apache.avro.io.EncoderFactory
import org.apache.avro.generic.GenericDatumReader
import org.apache.avro.generic.GenericData.Record
import org.apache.avro.io.{DecoderFactory, EncoderFactory}

import java.io.ByteArrayOutputStream

@AvroRecord
case class Platform (
  var deviceId: Option[String],
  var deviceType: Option[String]
)

@AvroRecord
case class Quality (
  var bitrate: Option[Int],
  var previousBitrate: Option[Int]
)

@AvroRecord
case class Playback (
  var quality: Option[Quality]
)

@AvroRecord
case class AtomicSlice (
  var timestamp_received: Long,
  var platform: Option[Platform],
  var playback: Option[Playback]
)

object ASMain {

  def main(args: Array[String]) = {

    val platform = Platform(deviceId=None, deviceType=Some("abc"))

    val as = AtomicSlice(
      timestamp_received=1234567890000L,
      platform=Some(platform),
      playback=None)

    println(as.toString)
    println(AtomicSlice.SCHEMA$)

    val sw = new SpecificDatumWriter[AtomicSlice](AtomicSlice.SCHEMA$)

    val out = new java.io.ByteArrayOutputStream()
    val encoder = EncoderFactory.get().binaryEncoder(out, null)
    sw.write(as, encoder)
    encoder.flush
    val ba = out.toByteArray
    out.close

    val reader = new GenericDatumReader[Record](AtomicSlice.SCHEMA$)

    val decoder = DecoderFactory.get().binaryDecoder(ba, null)
    val decoded = reader.read(null, decoder)

    println(decoded.toString)

  }
}

```
Here is the build.sbt
```
name := "domain-model"

version := "1.0"

//scalaVersion := "2.10.5"

resolvers += Resolver.sonatypeRepo("releases")

addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0-M5" cross CrossVersion.full)

libraryDependencies ++= Seq(
  "com.julianpeeters" % "avro-scala-macro-annotations_2.10" % "0.4"
)

```
Here is the error:
```
[info] Compiling 1 Scala source to /Users/mahesh/TWC/MaprVagrant/domain-model/target/scala-2.10/classes...
[error] /Users/mahesh/TWC/MaprVagrant/domain-model/src/main/scala/com/twc/needle/domain/AtomicSlice.scala:49: value SCHEMA$ is not a member of object com.twc.needle.domain.AtomicSlice
[error]     println(AtomicSlice.SCHEMA$)
[error]                         ^
[error] /Users/mahesh/TWC/MaprVagrant/domain-model/src/main/scala/com/twc/needle/domain/AtomicSlice.scala:51: value SCHEMA$ is not a member of object com.twc.needle.domain.AtomicSlice
[error]     val sw = new SpecificDatumWriter[AtomicSlice](AtomicSlice.SCHEMA$)
[error]                                                               ^
[error] /Users/mahesh/TWC/MaprVagrant/domain-model/src/main/scala/com/twc/needle/domain/AtomicSlice.scala:60: value SCHEMA$ is not a member of object com.twc.needle.domain.AtomicSlice
[error]     val reader = new GenericDatumReader[Record](AtomicSlice.SCHEMA$)
[error]                                                             ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 2 s, completed Jun 5, 2015 9:51:13 AM
[mahesh@trishul:~/TWC/MaprVagrant/domain-model]$
```

**Comment by julianpeeters** [comment]
For 0.4/Scala 2.10, you'll have to get the schema from an instance of the record: 

```scala
    val sw = new SpecificDatumWriter[AtomicSlice](as.getSchema)
```

The static `SCHEMA$` was added later in an effort to mimic the Java API

**Comment by sutram** [comment]
Ok, got it.

**Comment by sutram** [comment]
Ok, I am getting a different error with Scala 2.10

```
[info] Compiling 1 Scala source to /Users/mahesh/TWC/MaprVagrant/domain-model/target/scala-2.10/classes...
[error]
[error]      while compiling: /Users/mahesh/TWC/MaprVagrant/domain-model/src/main/scala/com/twc/needle/domain/AtomicSlice.scala
[error]         during phase: xsbt-dependency
[error]      library version: version 2.10.5
[error]     compiler version: version 2.10.5
[error]   reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMac
hines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/Jav$
VirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/classes:/Users/mahesh/$
ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.5.jar -classpath /Users/mahesh/TWC/MaprVagrant/domain-model/target/scala-2.10/classes:/Users/mahesh/.ivy2/cache/com.julianpeeters/avro-scala-macro-annotations_2.10/jars/avro$
scala-macro-annotations_2.10-0.4.jar:/Users/mahesh/.ivy2/cache/org.apache.avro/avro/bundles/avro-1.7.6.jar:/Users/mahesh/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.9.13.jar:/Users/mahesh/.ivy2/cache/org.cod$
haus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.9.13.jar:/Users/mahesh/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.0.5.jar:/Users/mahesh/.ivy2/cache/org.apache.commons/commons-compress/jars/commons-compress-$
.4.1.jar:/Users/mahesh/.ivy2/cache/org.tukaani/xz/jars/xz-1.0.jar:/Users/mahesh/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.4.jar:/Users/mahesh/.ivy2/cache/org.scalamacros/quasiquotes_2.10/jars/quasiquotes_2.10-2.0.0.jar:/Users/ma$
esh/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/Users/mahesh/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.10.jar:/Users/mahesh/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.10.jar:/Users/mah$
sh/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.10.jar:/Users/mahesh/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/Users/mahesh/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.0.jar:/Users$
mahesh/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.0.jar -Xplugin:/Users/mahesh/.ivy2/cache/org.scalamacros/paradise_2.10.5/jars/paradise_2.10.5-2.1.0-M5.jar -Yfundep-materialization
[error]
[error]   last tree to typer: Throw
[error]               symbol: null
[error]    symbol definition: null
error]                  tpe: Nothing
[error]        symbol owners:
[error]       context owners: value decoded -> method main -> object ASMain -> package domain
.
.
.
.
java.lang.NullPointerException
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser$$anonfun$1.isDefinedAt(Dependency.scala:132)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser$$anonfun$1.isDefinedAt(Dependency.scala:131)
        at xsbt.Dependency$CollectTypeTraverser.traverse(Dependency.scala:89)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:134)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:104)
        at scala.reflect.internal.Trees$$anonfun$itraverse$5.apply$mcV$sp(Trees.scala:1119)
        at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1118)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:149)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:104)
        at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2829)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:138)
        at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:104)
        at scala.reflect.internal.Trees$$anonfun$itraverse$2.apply$mcV$sp(Trees.scala:1107)
        at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1106)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
.
.
.
```
I snipped some of the error so let me know if you need a more complete error log

Thanks,
Sutram

**Comment by julianpeeters** [comment]
Make sure to use sbt 0.13.8+

In `project/build.properties`, use `sbt.version=0.13.8`.

Sorry you ran into this one, I'll make a note in the readme.

**Comment by sutram** [comment]
Tried this and it works!
Thanks

**Comment by julianpeeters** [comment]
excellent
